export * from './administrador.repository';
export * from './asesor.repository';
export * from './ciudad.repository';
export * from './cliente.repository';
export * from './departamento.repository';
export * from './lugar.repository';
export * from './solicitud.repository';
export * from './tarjeta.repository';
export * from './vehiculo.repository';
